apiVersion: v1
kind: Namespace
metadata:
  name: k8s-security-insecure
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted